// Generated by CoffeeScript 1.7.1
module.exports = function(uri) {
  return this.all(uri, function(req, res, next) {
    var header, headers, _i, _len;
    headers = [
      {
        name: 'Access-Control-Allow-Origin',
        value: '*'
      }, {
        name: 'Access-Control-Allow-Methods',
        value: req.headers['access-control-request-method']
      }, {
        name: 'Access-Control-Allow-Headers',
        value: req.headers['access-control-request-headers']
      }
    ];
    for (_i = 0, _len = headers.length; _i < _len; _i++) {
      header = headers[_i];
      res.header(header.name, header.value);
    }
    if (req.method === 'OPTIONS') {
      return res.send(200);
    } else {
      return next();
    }
  });
};
